# Generated by Django 2.1.4 on 2019-02-22 15:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examination', '0002_auto_20190222_2249'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='평가')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='추가 시간')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.ExaminationInfo', verbose_name='커리큘럼')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '시험평가',
                'verbose_name_plural': '시험평가',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0, verbose_name='数据id')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='추가 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 수집',
                'verbose_name_plural': '사용자 수집',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='사용자')),
                ('message', models.CharField(max_length=500, verbose_name='메세지')),
                ('has_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='추가 시간')),
            ],
            options={
                'verbose_name': '사용자 정보',
                'verbose_name_plural': '사용자 정보',
            },
        ),
    ]
