# Generated by Django 2.1.4 on 2022-05-27 07:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0002_auto_20190222_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testpaperinfo',
            options={'verbose_name': '시험지 정보', 'verbose_name_plural': '시험지 정보'},
        ),
        migrations.AlterModelOptions(
            name='testpapertestq',
            options={'verbose_name': '시험 문제 정보', 'verbose_name_plural': '시험 문제 정보'},
        ),
        migrations.AlterModelOptions(
            name='testscores',
            options={'verbose_name': '학생 성적 정보', 'verbose_name_plural': '학생 성적 정보'},
        ),
        migrations.AlterField(
            model_name='testpaperinfo',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='testpaperinfo',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='교수'),
        ),
        migrations.AlterField(
            model_name='testpaperinfo',
            name='edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='testpaperinfo',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='시험지 이름'),
        ),
        migrations.AlterField(
            model_name='testpaperinfo',
            name='passing_score',
            field=models.IntegerField(default=60, verbose_name='합격점'),
        ),
        migrations.AlterField(
            model_name='testpaperinfo',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.SubjectInfo', verbose_name='시험지 과목'),
        ),
        migrations.AlterField(
            model_name='testpaperinfo',
            name='total_score',
            field=models.IntegerField(default=100, verbose_name='총점'),
        ),
        migrations.AlterField(
            model_name='testpaperinfo',
            name='tp_degree',
            field=models.CharField(choices=[('jd', '쉬움'), ('zd', '중간'), ('kn', '어려움')], default='jd', max_length=2, verbose_name='시험지 난이도'),
        ),
        migrations.AlterField(
            model_name='testpapertestq',
            name='test_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpaper.TestPaperInfo', verbose_name='시험지'),
        ),
        migrations.AlterField(
            model_name='testpapertestq',
            name='test_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testquestion.TestQuestionInfo', verbose_name='시험 문제'),
        ),
        migrations.AlterField(
            model_name='testscores',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='testscores',
            name='test_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpaper.TestPaperInfo', verbose_name='시험지 정보'),
        ),
        migrations.AlterField(
            model_name='testscores',
            name='test_score',
            field=models.IntegerField(default=0, verbose_name='시험 성적'),
        ),
        migrations.AlterField(
            model_name='testscores',
            name='user',
            field=models.ForeignKey(on_delete=models.Model, to='user.StudentsInfo', verbose_name='학생 정보'),
        ),
    ]
