# Generated by Django 2.1.4 on 2019-02-22 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='시험 명칭')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='종료 시간')),
                ('student_num', models.IntegerField(default=0, verbose_name='참가 인원수')),
                ('actual_num', models.IntegerField(default=0, verbose_name='실제 참가자 수')),
                ('exam_state', models.CharField(choices=[('0', '시험 준비'), ('1', '시험 진행 중'), ('2', '시험 끝')], default='0', max_length=1, verbose_name='시험 상태')),
                ('exam_type', models.CharField(choices=[('pt', '보통'), ('ts', '특별')], default='pt', max_length=2, verbose_name='유형')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='생성 시간')),
            ],
            options={
                'verbose_name': '시험 정보',
                'verbose_name_plural': '시험 정보',
            },
        ),
        migrations.CreateModel(
            name='ExamPaperInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '시험지 정보',
                'verbose_name_plural': '시험지 정보',
            },
        ),
        migrations.CreateModel(
            name='ExamStudentsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.ExaminationInfo', verbose_name='시험 정보')),
            ],
            options={
                'verbose_name': '수험생 정보',
                'verbose_name_plural': '수험생 정보',
            },
        ),
    ]
