# Generated by Django 2.1.4 on 2022-05-27 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_auto_20190222_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationinfo',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='examinationinfo',
            name='exam_state',
            field=models.CharField(choices=[('0', '시험 전'), ('1', '시험 중'), ('2', '시험 종료')], default='0', max_length=1, verbose_name='시험 상태'),
        ),
        migrations.AlterField(
            model_name='examinationinfo',
            name='exam_type',
            field=models.CharField(choices=[('pt', '보통'), ('ts', '특수')], default='pt', max_length=2, verbose_name='유형'),
        ),
        migrations.AlterField(
            model_name='examinationinfo',
            name='student_num',
            field=models.IntegerField(default=0, verbose_name='참가자 수'),
        ),
    ]
