# Generated by Django 2.1.4 on 2019-02-22 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(default='', max_length=100, verbose_name='옵션')),
                ('is_right', models.BooleanField(default=True, verbose_name='정답 여부')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='생성 시간')),
            ],
            options={
                'verbose_name': '문제 선택 정보',
                'verbose_name_plural': '문제 선택 정보',
            },
        ),
        migrations.CreateModel(
            name='TestQuestionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500, verbose_name='시험 문제 제목')),
                ('score', models.IntegerField(default=0, verbose_name='성적')),
                ('tq_type', models.CharField(choices=[('xz', '선택'), ('pd', '판단'), ('tk', '빈칸 채우기')], default='xz', max_length=2, verbose_name='시험 문제 유형')),
                ('tq_degree', models.CharField(choices=[('jd', '쉬움'), ('zd', '중간'), ('kn', '어려움')], default='jd', max_length=2, verbose_name='시험 문제 난이도')),
                ('image', models.ImageField(max_length=200, upload_to='test_question/%Y/%m', verbose_name='시험 문제 사진')),
                ('is_del', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('is_share', models.BooleanField(default=False, verbose_name='공유 여부')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='생성 시간')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
            options={
                'verbose_name': '시험 문제 정보',
                'verbose_name_plural': '시험 문제 정보',
            },
        ),
    ]
